<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.1</version>
		<relativePath/>
	</parent>

	<groupId>com.codex</groupId>
	<artifactId>codex</artifactId>
	<version>1.0.0</version>
	<name>codex</name>
	<description>codex</description>
	<packaging>pom</packaging>

	<properties>
		<java.version>21</java.version>
		<mybatis-flex.version>1.9.3</mybatis-flex.version>
		<hutool.version>5.8.29</hutool.version>
		<fastjson2.version>2.0.51</fastjson2.version>
	</properties>

	<modules>
		<!-- 通用接口 -->
		<module>codex-api</module>
		<module>codex-core</module>
		<!-- 管理后台 -->
        <module>codex-admin</module>
		<!-- 登录鉴权模块 -->
		<module>codex-security</module>
		<!-- 通用Mapper -->
		<module>codex-mapper</module>
		<!-- 缓存模块 -->
		<module>codex-cache</module>
	</modules>

	<repositories>
		<repository>
			<id>aliyun-maven</id>
			<name>Aliyun Maven Repository</name>
			<url>https://maven.aliyun.com/nexus/content/groups/public/</url>
		</repository>
	</repositories>

	<dependencyManagement>
		<dependencies>
			<!--MyBatisFlex版本-->
			<dependency>
				<groupId>com.mybatis-flex</groupId>
				<artifactId>mybatis-flex-dependencies</artifactId>
				<version>${mybatis-flex.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<!--HuTool工具包版本-->
			<dependency>
				<groupId>cn.hutool</groupId>
				<artifactId>hutool-bom</artifactId>
				<version>${hutool.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<!--FastJson2版本-->
			<dependency>
				<groupId>com.alibaba.fastjson2</groupId>
				<artifactId>fastjson2</artifactId>
				<version>${fastjson2.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.github.xiaoymin</groupId>
			<artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
			<version>4.4.0</version>
		</dependency>
	</dependencies>
</project>
