server:
  port: 9999
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://sh-cdb-ga617of6.sql.tencentcdb.com:63895/codex_admin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: eO,+9XvT-u@i+c|%D=
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: 49.235.125.92
      port: 6379
      database: 0
      password: 'pl,okm123'
      timeout: 10s
# codex项目配置
codex:
  db:
    ddl-auto: true
  response-advice-packages: com.codex.admin
  security:
    token:
      secret: HjXtbpyg5U5V33bKnQPwUBauqxGKzynt
      duration: 2h
    captcha:
      image:
        enable: true
        length: 4
        duration: 5m
      email:
        enable: true
        account: 15021688037@163.com
        password: CHRSDWJPZNIKTUCV
        subject: 您有一个新的验证码
      sms:
        enable: true